services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: erp-frontend-container
    ports:
      - "3000:3000"
    networks:
      - erp-network
    restart: unless-stopped

networks:
  erp-network:
    driver: bridge