export default {
    gantt: {
        "Task name": "Название",
        "Start date": "Начало",
        "Add task": "Добавить задачу",
        Duration: "Длительность",
        Task: "Задача",
        Milestone: "Веха",
        "Summary task": "Сводная задача",

        Save: "Сохранить",
        Delete: "Удалить",
        Name: "Название",
        Description: "Описание",
        "Select type": "Выберите тип",
        Type: "Тип",
        "End date": "Окончание",
        Progress: "Прогресс",
        Predecessors: "Предшественники",
        Successors: "Последователи",
        "Add task name": "Введите название задачи",
        "Add description": "Введите описание",
        "Select link type": "Выберите тип связи",
        "End-to-start": "Окончание-начало",
        "Start-to-start": "Начало-начало",
        "End-to-end": "Окончание-окончание",
        "Start-to-end": "Начало-окончание",

        Add: "Добавить",
        "Child task": "Подзадача",
        "Task above": "Задачу выше",
        "Task below": "Задачу ниже",
        "Convert to": "Преобразовать в",
        Edit: "Редактировать",
        Cut: "Вырезать",
        Copy: "Копировать",
        Paste: "Вставить",
        Move: "Переместить",
        Up: "Вверх",
        Down: "Вниз",
        Indent: "Увеличить отступ",
        Outdent: "Уменьшить отступ",
        "Split task": "Разделить задачу",
        Segment: "Сегмент",

        "New task": "Новая задача",
        "Move up": "Переместить вверх",
        "Move down": "Переместить вниз",
        Undo: "Отменить",
        Redo: "Повторить",

        Week: "Неделя",
        Q: "Квартал",

        Apr: "Апрель"
    },
    grid: {
        "Add before": "Добавить до",
        "Add after": "Добавить после",
        Cut: "Вырезать",
        Copy: "Копировать",
        Paste: "Вставить",
        Delete: "Удалить",
        "New row": "Новая строка",
        "Move up": "Переместить вверх",
        "Move down": "Переместить вниз",
        Undo: "Отменить",
        Redo: "Повторить",
    },
};